<?php
require_once("../class/database.php");
$db = new Database();
$info=array(
	/* Template:

	".mp3"=>array( //file name of the mp3.
		"title"=>"",
		"date"=>"",
		"comment" => "",
		"description" => 	"",
		"cover"=>"",//a cover images listed in the covers folder.
		"markers"=>array(
			"" => array( //The second the marker appears, decimals accepted. 
				"trackname"=>"",
				"artist"=>"",
				"album"=>"",
				"circle"=>"",
				"comment"=>"",
				"year"=>"",
			),
		),
	),
	*/
	"papa_petes_-_whats_hard_core_~_comiket_style_(C83).mp3"=>array(
		"title"=>"Papa Pete's: What's Hard? Core ~ Comiket Style (C83)",
		"date"=>"12/9/2013",
		"bpm"=>"175",
		"offset"=>"",
		"comment" => "J-core 128bpm Otaku Hardcore Style",
		"description" => 	"This is the best of Hardcore that I could find/use from Comiket 83. Overall, it's kind of meh, ".
							"but there are a few really good songs in it. I also experimented with a few new ideas. One of them being an ".
							"echo drop. Which I think I'm starting to get the hang of. Just remember these are my rehersals not actual ".
							"shows. So I tend to experiment and play around a little more during these.",
		"cover"=>"nothankyou-small.png",
		"markers"=>array(
			"0" => array(
				"trackname"=>"Loberia",
				"artist"=>"aran",
				"album"=>"Desktop Universe",
				"circle"=>"Unitone",
				"comment"=>"",
				"year"=>"2012",
			),
			"288" => array(
				"trackname"=>"stabilizer (effected by PHQUASE)",
				"artist"=>"PHQUASE",
				"album"=>"Voltage Ignition",
				"circle"=>"Movement on the FLOOR",
				"comment"=>"",
				"year"=>"2012",
			),
			"636" => array(
				"trackname"=>"Mad Futurist",
				"artist"=>"Daisuke Ohnuma vs D.F.K.Soundsystem",
				"album"=>"Voltage Ignition",
				"circle"=>"Movement on the FLOOR",
				"comment"=>"",
				"year"=>"2012",
			),
			"885" => array(
				"trackname"=>"Rain Injector",
				"artist"=>"LV.4",
				"album"=>"Bon Voyage!!",
				"circle"=>"CODE-49",
				"comment"=>"",
				"year"=>"2012",
			),
			"1288" => array(
				"trackname"=>"HARDCODE (2012 Update)",
				"artist"=>"aran",
				"album"=>"Desktop Universe",
				"circle"=>"Unitone",
				"comment"=>"",
				"year"=>"2012",
			),
			"1600" => array(
				"trackname"=>"Collect the wonders",
				"artist"=>"Nepuripi",
				"album"=>"Club in the XANADU",
				"circle"=>"dennoh-STYLE",
				"comment"=>"",
				"year"=>"2012",
			),
			"1873" => array(
				"trackname"=>"Uplift (affected edit)",
				"artist"=>"源屋",
				"album"=>"Voltage Ignition",
				"circle"=>"Movement on the FLOOR",
				"comment"=>"Hope nobody really liked this song. :p This is where I messed up. I was playing around with some new techniques and I messed up and bumped my needle search. But oh well, lol, it's a rehersal. It almost sounds intentional, which is odd.",
				"year"=>"2012",
			),
			"2175" => array(
				"trackname"=>"Empty Skydiving",
				"artist"=>"BlackY",
				"album"=>"Voltage Ignition",
				"circle"=>"Movement on the FLOOR",
				"comment"=>"",
				"year"=>"2012",
			),
			"2456" => array(
				"trackname"=>"HURT",
				"artist"=>"SHU10",
				"album"=>"Club in the XANADU",
				"circle"=>"dennoh-STYLE",
				"comment"=>"",
				"year"=>"2012",
			),
			"2645" => array(
				"trackname"=>"Aquila",
				"artist"=>"aran feat. lawy",
				"album"=>"Desktop Universe",
				"circle"=>"Unitone",
				"comment"=>"",
				"year"=>"2012",
			),
			"3010" => array(
				"trackname"=>"Shall We Dance On Graveyard",
				"artist"=>"Vorbis",
				"album"=>"Club in the XANADU",
				"circle"=>"dennoh-STYLE",
				"comment"=>"",
				"year"=>"2012",
			),
			"3214" => array(
				"trackname"=>"Lead your mind",
				"artist"=>"Re-Te",
				"album"=>"Club in the XANADU",
				"circle"=>"dennoh-STYLE",
				"comment"=>"It seems like a short song, but really it's just a lot of overlap.",
				"year"=>"2012",
			),
			"3387" => array(
				"trackname"=>"God's Meta-Material",
				"artist"=>"ponica",
				"album"=>"Club in the XANADU",
				"circle"=>"dennoh-STYLE",
				"comment"=>"",
				"year"=>"2012",
			),
			"3701" => array(
				"trackname"=>"Cowardly Clime",
				"artist"=>"rider",
				"album"=>"Femt Fiber",
				"circle"=>"ネコノツカ",
				"comment"=>"",
				"year"=>"2012",
			),
		),
	),

	"papa_petes_-_whats_an_edm_~_comiket_style_(C83).mp3"=>array(
		"title"=>"Papa Pete's: What's an EDM? ~ Comiket Style (C83)",
		"date"=>"12/2/2013",
		"bpm"=>"128",
		"offset"=>"",
		"comment" => "J-core 128bpm Otaku Club Style",
		"description" => 	"For this night, I wanted to do stuff that's new(-ish) in Japan. With all music from the 2012 Winter Comiket, I ".
							"broght my favorite choices in club music. Comiket is a large Manga, Anime, and Video Game convention held ".
							"each year in Odaiba Japan, right out side of Tokyo. I really loved how this playlist turned out, and would ".
							"love to play more stuff like this again! As you can probably tell, I broke one of my rules for Papa Pete's. ".
							"This time I actually played a song with Japanese lyrics. I couldn't resist, it was too perfect of a show ".
							"opener. The highlight of this set is, \"Download\" by \"en; Dolphin Records\". It can be found on their ".
							"\"Eternal Dark Madness\" (That's right EDM) album. So I hope you enjoy!",
		"cover"=>"papapetes-comiket1.png",
		"markers"=>array(
			"0" => array(
				"trackname"=>"Clockup Flowers",
				"artist"=>"ランコ",
				"album"=>"マジコカタストロフィ",
				"circle"=>"",
				"comment"=>"",
				"year"=>"2012",
			),
			"590" => array(
				"trackname"=>"The Legend Of Cirno",
				"artist"=>"IOSYS",
				"album"=>"> TOHO EDM <",
				"circle"=>"IOSYS",
				"comment"=>"Is it Dead Touhou? Touhou Mouse? Buh... 'cept, what is this? The strongest song? Either way, I highly recommend checking out this album if you love Touhou.",
				"year"=>"2012",
			),
			"846" => array(
				"trackname"=>"Download",
				"artist"=>"",
				"album"=>"Eternal Dark Madness",
				"circle"=>"en; Dolphin Records",
				"comment"=>"A very good album. It's rare, and nearly impossible to get in the US, but if we all come together and show a demand for their music, they may just ".
							"release the album here, or on a site that has US accessiblity! For now, you can check it out on youtube: <a href='http://www.youtube.com/playlist?list=PLp4Uw1OKEozMzM5nA707cg62JrVWMkZTo'>EDM</a>",
				"year"=>"2012",
			),
			"1125" => array(
				"trackname"=>"In Sight Girl",
				"artist"=>"Yuuna Kamishiro",
				"album"=>"標 -MILESTONE-",
				"circle"=>"俺++(Includeore)",
				"comment"=>"",
				"year"=>"2012",
			),
			"1413" => array(
				"trackname"=>"邪気 IN 眼NGSTA",
				"artist"=>"",
				"album"=>"Eternal Dark Madness",
				"circle"=>"en; Dolphin Records",
				"comment"=>"Another awesome song from the EDM album by en; Dolphin Records.",
				"year"=>"2012",
			),
			"1672" => array(
				"trackname"=>"Bad Shit",
				"artist"=>"aran",
				"album"=>"Desktop Universe",
				"circle"=>"Unitone",
				"comment"=>"Not sure why it's called, 'Bad Shit'. LOL, it's a pretty good song.",
				"year"=>"2012",
			),
			"1920" => array(
				"trackname"=>"Tonight the Night",
				"artist"=>"Chen-U",
				"album"=>"Aria of Innocence",
				"circle"=>"発熱巫女～ず",
				"comment"=>"",
				"year"=>"2012",
			),
			"2092" => array(
				"trackname"=>"猫と硝子と円い月 (Black lingerie mix)",
				"artist"=>"kaguraduki",
				"album"=>"Luxurious Cattail",
				"circle"=>"Lost Garden",
				"comment"=>"I think it translates to, 'The cat, the glass, and the round moon'. Not sure.",
				"year"=>"2012",
			),
			"2411" => array(
				"trackname"=>"Star Gear",
				"artist"=>"Junk",
				"album"=>"Voltage Ignition",
				"circle"=>"Movement on the FLOOR",
				"comment"=>":D Tales of Phantasia! Never expected to here that.",
				"year"=>"2012",
			),
			"2700" => array(
				"trackname"=>"Summer Season Has Come",
				"artist"=>"Tomohiko Togashi",
				"album"=>"Snowdrop",
				"circle"=>"Black Berry Recordings",
				"comment"=>"",
				"year"=>"2012",
			),
			"3007" => array(
				"trackname"=>"Deep Under",
				"artist"=>"Ottiki&Charlotte",
				"album"=>"Ogre's HARDCORE",
				"circle"=>"Snow*Mark",
				"comment"=>"",
				"year"=>"2012",
			),
			"3273" => array(
				"trackname"=>"ともしび (Riff-rain mix)",
				"artist"=>"kaguraduki",
				"album"=>"Luxurious Cattail",
				"circle"=>"Lost Garden",
				"comment"=>"",
				"year"=>"2012",
			),
			"3565" => array(
				"trackname"=>"Cloud 9",
				"artist"=>"aran",
				"album"=>"Desktop Universe",
				"circle"=>"Unitone",
				"comment"=>"",
				"year"=>"2012",
			),
			"3971" => array(
				"trackname"=>"Naloxone",
				"artist"=>"Kefy",
				"album"=>"ナナイロチック",
				"circle"=>"fractaleline",
				"comment"=>"",
				"year"=>"2012",
			),
		),
	),

	"papa_petes_-_this_is_j-core.mp3"=>array(
		"title"=>"Papa Pete's: J-CORE です！ (This is J-Core)",
		"date"=>"11/25/2013",
		"bpm"=>"170",
		"offset"=>"",
		"comment" => "J-core 170bpm Pure J-Core Style",
		"description" => 	"For this week, I was given special permission to play 'Wide Awake' by Noizencio, so I focused on music that would compliment it. But what I realized when building this ".
							"set, that it was a pure J-Core (Japanese Hardcore) set, my favorite kind of EDM music. :D So, if you want a reference as to what J-Core really is, this set is a good starting point. The ".
							"album image was chosen, because this is the kind of vibe I get from the song, 'Wide Awake'. I would like to, if I ever make an official release of this song, replace ".
							"the image of Shana with something similiarly drawn with a unique character.".
							'<img src="/dj/img/easteregg.png" onclick=\'$("audioOBJ").currentTime = 3150.7;$("audioOBJ").play(1);setTimeout(function(){$("audioOBJ").pause();},1420);\' style="right:0px;top:0px;position:absolute;cursor:pointer">',
		"cover"=>"jcore.png",
		"markers"=>array(
			"0" => array(
				"trackname"=>"IT'S TIME TO SCREAM",
				"artist"=>"DELAY SYSTEM",
				"album"=>"LAND OF PASSION",
				"circle"=>"DJ DEPATH&M-Project",
				"comment"=>"Touuuuuuuuuu-Hou.",
				"year"=>"2008",
			),
			"134" => array(
				"trackname"=>"サトリムソウ",
				"artist"=>"ビートまりお",
				"album"=>"200%東方カーニバル",
				"circle"=>"東方カーニバル",
				"comment"=>"",
				"year"=>"2011",
			),
			"367" => array(
				"trackname"=>"Wide Awake (feat. Katy Perry)",
				"artist"=>"Noizenecio",
				"album"=>"n/a",
				"circle"=>"n/a",
				"comment"=>"This week, I got special permission from my friend Noizencio, to use his newest song. ",
				"year"=>"2013",
			),
			"746" => array(
				"trackname"=>"Nothing Compares 2 U",
				"artist"=>"yukacco",
				"album"=>"200%東方カーニバル",
				"circle"=>"",
				"comment"=>"東方カーニバル",
				"year"=>"2011",
			),
			"1068" => array(
				"trackname"=>"DOUBLE DRAGON",
				"artist"=>"RaverRose",
				"album"=>"THE GAME ADICTS!!",
				"circle"=>"Cis-Trance",
				"comment"=>"",
				"year"=>"2004",
			),
			"1360" => array(
				"trackname"=>"HALO",
				"artist"=>"JORDI K-STANYA vs DJ VIC",
				"album"=>"UNDERGROUND MAKINA CONNECTIONZ VOL.8",
				"circle"=>"BURNING CHROME RECORDS",
				"comment"=>"",
				"year"=>"2011",
			),
			"1733" => array(
				"trackname"=>"DREAM UP (Innocent Riot mix)",
				"artist"=>"DJ SHIMAMURA",
				"album"=>"DiGiTAL GENERATiON EP",
				"circle"=>"HARDCORE TANO*C",
				"comment"=>"",
				"year"=>"2007",
			),
			"2148" => array(
				"trackname"=>"Dreamin' Night",
				"artist"=>"Hommarju",
				"album"=>"SKETCH BOOK! ANTHOLOGY 2 - Disc:02 Friendship side",
				"circle"=>"SKETCH UP! Recordings",
				"comment"=>"",
				"year"=>"2011",
			),
			"2511" => array(
				"trackname"=>"Makin' Love",
				"artist"=>"P*Light",
				"album"=>"Are You Happy?",
				"circle"=>"pichnopop",
				"comment"=>"",
				"year"=>"2011",
			),
			"2756" => array(
				"trackname"=>"GO MAD AND DIE",
				"artist"=>"chocoxina",
				"album"=>"匪天",
				"circle"=>"不可逆ハードコア",
				"comment"=>"Choco-?bo? Kupo.",
				"year"=>"2012",
			),
			"3141" => array(
				"trackname"=>"SHADOW",
				"artist"=>"DJ MEET",
				"album"=>"UNDERGROUND MAKINA CONNECTIONZ VOL.3",
				"circle"=>"BURNING CHROME RECORDS",
				"comment"=>"",
				"year"=>"2009",
			),
			"3636" => array(
				"trackname"=>"魔理沙に大変な役でハコにされました (カラオケVer)",
				"artist"=>"ARM",
				"album"=>"ねこみことかのからおけ",
				"circle"=>"IOSYS",
				"comment"=>	"I think this actually translates to, 'The box has been very useful to Marissa'. Though everyone calls it instead, 'Marisa Stole The Precious Thing' It's ".
							"a Touhou song. :D This is an off-vocal version, because of the audience I'm dealing with.",
				"year"=>"2008",
			),
			"3843" => array(
				"trackname"=>"Ascension",
				"artist"=>"Noizenecio",
				"album"=>"Japanese Stream Hardcore Vol.2",
				"circle"=>"Japanese Stream Hardcore",
				"comment"=>"",
				"year"=>"2012",
			),
			"4161" => array(
				"trackname"=>"Flower Stream -Trancecore mix-",
				"artist"=>"源屋",
				"album"=>"FANATIC HARDCORE BLACK LABEL",
				"circle"=>"Cis-Trance",
				"comment"=>"",
				"year"=>"2008",
			),
			"4556" => array(
				"trackname"=>"Aorta Overdrive",
				"artist"=>"Shaman Cure-All",
				"album"=>"RAZE",
				"circle"=>"Roar Records",
				"comment"=>"",
				"year"=>"2009",
			),
			"4885" => array(
				"trackname"=>"Bleep Code",
				"artist"=>"The 4th",
				"album"=>"Ways For Liberation DISC.2",
				"circle"=>"kors k",
				"comment"=>"",
				"year"=>"2010",
			),
			"5130" => array(
				"trackname"=>"GOOD LUCK, BE HAPPY!!",
				"artist"=>"すもも",
				"album"=>"PLUG IN PLUG OUT",
				"circle"=>"A-One",
				"comment"=>"And yet again, a, 'I've been up here too long, suger coated, tooth breaking' song. ^◡◡^ And remember, ★be happy★",
				"year"=>"2010",
			),
		),
	),

	"papa_petes_-_yukkuri_ja_nai.mp3"=>array(
		"title"=>"Papa Pete's: YUKKURI じゃない。。。",
		"date"=>"11/18/2013",
		"bpm"=>"135",
		"offset"=>"",
		"comment" => "J-core 135bpm Funky Grab Bag of Club Style",
		"description" => 	"This time the music was all over the place. Stuff that was Drum and Bass, typical club, dub step, blah blah blah. ".
							"But, the important part, is that it was also the first time I decided to experiment with Video. It took a very long time to ".
							"set this one up, so that's why I haven't done it again. But I really do want to, when I get time, try to do another video set like ".
							"this. The video isn't displayed here, But you can check that out on the video page.".
							"<img src='/dj/img/easteregg.png' onclick='$(\"audioOBJ\").currentTime = 4342;$(\"audioOBJ\").play();' style='right:0px;top:0px;position:absolute;cursor:pointer'>",
		"cover"=>"y4.png",
		"markers"=>array(
			"0" => array(
				"trackname"=>"Mortuary",
				"artist"=>"3x6",
				"album"=>"SUBMERGE",
				"circle"=>"Subroc Recordings",
				"comment"=>"",
				"year"=>"2010",
			),
			"100" => array(
				"trackname"=>"Roll you up",
				"artist"=>"Cherryboy Function",
				"album"=>"SPEEDKING VOL.3 Disc 1",
				"circle"=>"SPEEDKING PRODUCTIONS",
				"comment"=>"",
				"year"=>"2010",
			),
			"341" => array(
				"trackname"=>"HxCx JUNKIEEE (Black Ace -Cute Breaks Mix-)",
				"artist"=>"DJ DEPATH & M-Project",
				"album"=>"NO ALTERNATIVE+",
				"circle"=>"TERRAFORM MUSIC, Guhroovy",
				"comment"=>"",
				"year"=>"2010",
			),
			"673" => array(
				"trackname"=>"Freak",
				"artist"=>"fang",
				"album"=>"Driven' De:st-ructure2 -Heteronomy-",
				"circle"=>"Sound Ave.",
				"comment"=>"",
				"year"=>"2012",
			),
			"1017" => array(
				"trackname"=>"ADDICTRO",
				"artist"=>"DJ Miki",
				"album"=>"Hard Party!! ～The Reason of HAPPY NOSTALGIA～",
				"circle"=>"",
				"comment"=>"HAPPY NOSTALGIA",
				"year"=>"2012",
			),
			"1196" => array(
				"trackname"=>"A-Q-U-A",
				"artist"=>"HAPPY NOSTALGIA",
				"album"=>"MINOR SCORE",
				"circle"=>"",
				"comment"=>"",
				"year"=>"2012",
			),
			"1421" => array(
				"trackname"=>"Adagio for Summer Wind. (DJ SHARPNEL's bass:drive remix)",
				"artist"=>"清水準一",
				"album"=>"Deejay Busters!",
				"circle"=>"Key Sounds Label",
				"comment"=>"How does this sound anything like Summer?",
				"year"=>"2011",
			),
			"1701" => array(
				"trackname"=>"Be Your Star",
				"artist"=>"源屋",
				"album"=>"MINAMOTRANCE CORE 斬!!!",
				"circle"=>"MINAMOTRANCE",
				"comment"=>"",
				"year"=>"2008",
			),
			"2037" => array(
				"trackname"=>"Leberate (2013 uplift mix)",
				"artist"=>"源屋",
				"album"=>"Re:union",
				"circle"=>"MINAMOTRANCE",
				"comment"=>"",
				"year"=>"2013",
			),
			"2310" => array(
				"trackname"=>"Oxenman",
				"artist"=>"DJ 296",
				"album"=>"Privilege of Intersect Fractional.Vol.2",
				"circle"=>"Otaku Record",
				"comment"=>"",
				"year"=>"2007",
			),
			"2686" => array(
				"trackname"=>"Plan C",
				"artist"=>"Ryu☆",
				"album"=>"plan 8",
				"circle"=>"",
				"comment"=>"",
				"year"=>"2013",
			),
			"2902" => array(
				"trackname"=>"Mercury",
				"artist"=>"Hommarju",
				"album"=>"JP-H/D#03",
				"circle"=>"SKETCH UP! Recordings",
				"comment"=>"",
				"year"=>"2013",
			),
			"3267" => array(
				"trackname"=>"Immediately Arise an Elan",
				"artist"=>"fang",
				"album"=>"Fractalizer",
				"circle"=>"Sound Ave.",
				"comment"=>"",
				"year"=>"2011",
			),
			"3692" => array(
				"trackname"=>"bi135",
				"artist"=>"USAO",
				"album"=>"Far World",
				"circle"=>"",
				"comment"=>"The next two tracks are played almost simultaneous of each other. I mix between the two for next part.",
				"year"=>"2005",
			),
			"3708" => array(
				"trackname"=>"Sampling Rhythm Loop",
				"artist"=>"Remo-Con vs DJ TECHNORCH",
				"album"=>"中 ～Centrism～",
				"circle"=>"999 Recordings",
				"comment"=>"Mixed in with the previous song.",
				"year"=>"2011",
			),
			"4051" => array(
				"trackname"=>"DA★MANCO",
				"artist"=>"jea",
				"album"=>"ENDLESS SUMMER",
				"circle"=>"高速音楽隊シャープネル",
				"comment"=>'This song is the, "you\'ve left me up here for to long" song. LOL, I really like happy, silly, fun stuff. But I know a lot of people might not like this kind of thing. Either way, I still love it.',
				"year"=>"2000",
			),
		),
	),

	"papa_petes_-_yukkuri_desu_ka.mp3"=>array(
		"title"=>"Papa Pete's: Yukkuri Desu Ka¿",
		"date"=>"11/11/2013",
		"bpm"=>"128",
		"offset"=>"",
		"comment" => "J-core 128-134bpm Club Style",
		"description" => 	"This was one of the more popular sets I've done. There is a bit of an industrial sound to the whole mix, I think is what drew everybody in.".
							"But this mix focuses again, on the Yukkuri theme, of slower club music. The title is, 'Is this Yukkuri' in english. I ask this question, ".
							"because some of these songs do go slightly over 128bpm, and because I see people really move when they here this music. So I had to ask ".
							"myself, is this really Yukkuri? It's also a hint at how my feelings have changed over the weeks about club music.<br><br>".
							"The highlight group of this set was a group named, 'MISSILE CHEWBACCA', hence the cover being Machine Gun Chen.",
		"cover"=>"y3.png",
		"markers"=>array(
			"13" => array(
				"trackname"=>"Abend",
				"artist"=>"sta",
				"album"=>"僕はこの世界で地獄を見た",
				"circle"=>"salvation by faith records",
				"comment"=>"",
				"year"=>"2009",
			),
			"253" => array(
				"trackname"=>"R.N.O.Y.W. -Rave New Osasimi Yama World-",
				"artist"=>"hapi⇒",
				"album"=>"THE MEDLEY OF POKéMON RGBY+GSC -3PBs-",
				"circle"=>"salvation by faith records",
				"comment"=>"",
				"year"=>"2009",
			),
			"562" => array(
				"trackname"=>"See you (Camellia's Farewell Remix)",
				"artist"=>"Shandy Kubota",
				"album"=>"ShandyBass",
				"circle"=>"UOM Records",
				"comment"=>"",
				"year"=>"2012",
			),
			"852" => array(
				"trackname"=>"LMM",
				"artist"=>"Traffic Jammies",
				"album"=>"2010.5 DJmix",
				"circle"=>"Traffic Jammies Guest サイケアウツG",
				"comment"=>"",
				"year"=>"2010",
			),
			"926" => array(
				"trackname"=>"L Is Love",
				"artist"=>"Traffic Jammies",
				"album"=>"REGARDS",
				"circle"=>"NiTEFLARE",
				"comment"=>"",
				"year"=>"2011",
			),
			"1143" => array(
				"trackname"=>"U.S.D.Heaven",
				"artist"=>"MISSILE CHEWBACCA",
				"album"=>"J-CORE MASTERZ VOL.10",
				"circle"=>"MOB SQUAD BLACK LABEL",
				"comment"=>"",
				"year"=>"2011",
			),
			"1384" => array(
				"trackname"=>"Dirty Orange",
				"artist"=>"天音",
				"album"=>"OVER THE LIMITS!",
				"circle"=>"Tribullets",
				"comment"=>"",
				"year"=>"2010",
			),
			"1675" => array(
				"trackname"=>"Eidolon",
				"artist"=>"aran",
				"album"=>"Round Up Crystals EP",
				"circle"=>"aran",
				"comment"=>"",
				"year"=>"2012",
			),
			"1968" => array(
				"trackname"=>"Gloom",
				"artist"=>"fang",
				"album"=>"Verdure",
				"circle"=>"Sound Ave.",
				"comment"=>"",
				"year"=>"2012",
			),
			"2114" => array(
				"trackname"=>"next2next",
				"artist"=>"MISSILE CHEWBACCA",
				"album"=>"J-CORE MASTERZ VOL.9",
				"circle"=>"MOB SQUAD BLACK LABEL",
				"comment"=>"",
				"year"=>"2011",
			),
			"2409" => array(
				"trackname"=>"Elsie (Aura Qualic Remix)",
				"artist"=>"Morning Sprite",
				"album"=>"Sprite Impressions03 -THE NEXT GENERATION REMIXES-",
				"circle"=>"Sprite Recordings",
				"comment"=>"",
				"year"=>"2012",
			),
			"2585" => array(
				"trackname"=>"Cybernetic Angel",
				"artist"=>"源屋",
				"album"=>"MINAMOTRANCE CORE QUAD!!!!",
				"circle"=>"MINAMOTRANCE",
				"comment"=>"This one is tucked in there kind of deep.",
				"year"=>"2009",
			),
			"2970" => array(
				"trackname"=>"Extasy",
				"artist"=>"you",
				"album"=>"500 OVER!!",
				"circle"=>"Psycho Filth Records",
				"comment"=>"",
				"year"=>"2011",
			),
		),
	),


	"youmacon_-_touhou_-_yukkuri.mp3"=>array(
		"title"=>"TouuuuuuuuuHou~kkuri",
		"date"=>"11/2/2013",
		"bpm"=>"128",
		"offset"=>"",
		"comment" => "128bpm Club and Rave Style",
		"description" => 	"The point of the show was to Hijack some space at Youmacon, and expose people to the awesomeness that is Touhou; However ".
							"this is so not what ended up being played at Youmacon, but most of this was. So much happened at that convention, it's ".
							"impossible to have the whole thing recorded. So this mix is more of a, 'What it would have been like', kind of thing. ".
							"Despite all kinds of Touhou and J-core were played, teaching the anime kiddies what real Otaku-style music is.<br><br>".
							"I feel the mission was a complete success.",
		"cover"=>"y2.png",
		"markers"=>array(
			"6" => array(
				"trackname"=>"The Marisa (Dirty Spark)",
				"artist"=>"The Red Eyed Peas feat. Big Arrow, NTURN & SAISE",
				"album"=>"SAISENRETURN",
				"circle"=>"ALiCE'S EMOTiON ＆ Alstroemeria Records",
				"comment"=>"Li-i-i-i-i-i-i-i-i-i-i-ttle squirrel. :3",
				"year"=>"",
			),
			"327" => array(
				"trackname"=>"アリス→デレ",
				"artist"=>"ARM/miko",
				"album"=>"東方河想狗蒼池",
				"circle"=>"IOSYS",
				"comment"=>"This @#%& will rot your teeth out... But you gotta admit, can't listen to this without smiling.",
				"year"=>"2007",
			),
			"480" => array(
				"trackname"=>"innocent",
				"artist"=>"市松 椿/綾倉 盟",
				"album"=>"innocent",
				"circle"=>"TAK-sk/hiro.na",
				"comment"=>"",
				"year"=>"2008",
			),
			"663" => array(
				"trackname"=>"Lovelight",
				"artist"=>"Alstroemeria Records",
				"album"=>"Lovelight",
				"circle"=>"",
				"comment"=>"",
				"year"=>"わかりません。。。",
			),
			"754" => array(
				"trackname"=>"Teip",
				"artist"=>"Bart A LiCE",
				"album"=>"SAISEN TURN",
				"circle"=>"ALiCE'S EMOTiON ＆ Alstroemeria Records",
				"comment"=>"",
				"year"=>"2010",
			),
			"985" => array(
				"trackname"=>"CRIMSON ECLIPCE ～紅楼～",
				"artist"=>"SaiT",
				"album"=>"幻想のエリシオン",
				"circle"=>"anos+plus×SAVE THE QUEEN",
				"comment"=>"",
				"year"=>"2010",
			),
			"1270" => array(
				"trackname"=>"Dark Road",
				"artist"=>"Misato",
				"album"=>"HARMONY",
				"circle"=>"Alstroemeria Records",
				"comment"=>"",
				"year"=>"2007",
			),
			"1589" => array(
				"trackname"=>"Invisible Full Moon",
				"artist"=>"Haruna",
				"album"=>"For Your Pieces",
				"circle"=>"Alstroemeria Records",
				"comment"=>"",
				"year"=>"2008",
			),
			"1785" => array(
				"trackname"=>"Like A Shooting Star",
				"artist"=>"pyn",
				"album"=>"Like a shooting star.EP",
				"circle"=>"Aftergrow",
				"comment"=>"",
				"year"=>"2009",
			),
			"2017" => array(
				"trackname"=>"Night Drive from t'moon(Progressive/drv rmx)",
				"artist"=>"Iemitsu.",
				"album"=>"We Love the Toho Rmxes! DISC:04",
				"circle"=>"",
				"comment"=>"",
				"year"=>"",
			),
			"2144" => array(
				"trackname"=>"乙女のDeciSioN",
				"artist"=>"双月 彩",
				"album"=>"氷凜 HYO-RIN",
				"circle"=>"K2 SOUND",
				"comment"=>"",
				"year"=>"2010",
			),
			"2334" => array(
				"trackname"=>"I'm Alone",
				"artist"=>"Calvin ALiCE feat. Big Arrow",
				"album"=>"SAISENRETURN",
				"circle"=>"ALiCE'S EMOTiON ＆ Alstroemeria Records",
				"comment"=>"",
				"year"=>"2011",
			),
			"2639" => array(
				"trackname"=>"losT paradise",
				"artist"=>"隣人",
				"album"=>"a+jugos",
				"circle"=>"CYTOKINE",
				"comment"=>"",
				"year"=>"2009",
			),
			"2693" => array(
				"trackname"=>"Magic Girl",
				"artist"=>"Alstroemeria Records",
				"album"=>"Lovelight",
				"circle"=>"",
				"comment"=>"It's being used in the background for about 4 minutes, then plays out after the song ends.",
				"year"=>"",
			),
			"2995" => array(
				"trackname"=>"Magic Square",
				"artist"=>"坂上なち",
				"album"=>"Third Ensemble: Noir",
				"circle"=>"Alstroemeria Records",
				"comment"=>"",
				"year"=>"2010",
			),
			"3395" => array(
				"trackname"=>"Primitive Spring",
				"artist"=>"ゆきまめ",
				"album"=>"Clamshell Relation",
				"circle"=>"Digitalic Party",
				"comment"=>"",
				"year"=>"2010",
			),
			"3599" => array(
				"trackname"=>"4-dimension",
				"artist"=>"YUKI",
				"album"=>"technological",
				"circle"=>"FALSE&TRUES",
				"comment"=>"Definitely one of my favorites from this set list. Airy, fun, and something about the style in her voice.",
				"year"=>"2009",
			),
			"3706" => array(
				"trackname"=>"Cray-G Apple",
				"artist"=>"maelock",
				"album"=>"Apple Tree",
				"circle"=>"Attrielectrock",
				"comment"=>"This song kind of lurks for a while, and then smashes out.",
				"year"=>"2011",
			),
			"3788" => array(
				"trackname"=>"Crimson Glory-Aurtas Mix",
				"artist"=>"3L",
				"album"=>"Crimson Glory Remixies +",
				"circle"=>"NJK Record",
				"comment"=>"",
				"year"=>"2008",
			),
			"4056" => array(
				"trackname"=>"Kimi & Watashi",
				"artist"=>"deadmino4ma feat. Big Arrow",
				"album"=>"SAISENRETURN",
				"circle"=>"ALiCE'S EMOTiON ＆ Alstroemeria Records",
				"comment"=>"Another one of my favorites of this set.",
				"year"=>"2011",
			),
		),
	),


	"papa_petes_-_yukkuri.mp3"=>array(
		"title"=>"Papa Pete's: Yukkuri~.",
		"date"=>"11/4/2013",
		"bpm"=>"128",
		"offset"=>"",
		"comment" => "J-core 128bpm Club Style",
		"description" => 	"My biggest complaint on my first night was that the music I played, was 'too fast'. So I slowed it down a bit. 'Yukkuri' is a Japanese word, meaning 'relax'. ".
							"This setlist was nice, overall, though it wasn't my best. I loved the music, despite my grumbling about having to slow it down.<br><br> ".
							"<b>About Yukkuri</b><br>There is a meme surrounding Touhou, involving two of the main characters being drawn very poorly, and they look fat. This was later captioned with the word, ".
							"'Yukkuri'. Eventually the meme became taking any photo, making the subject appear fat, and then labeling it with the same tag line. ",
		"cover"=>"y1.png",
		"markers"=>array(
			"6" => array(
				"trackname"=>"Rave Launcher Mk. I",
				"artist"=>"Masayoshi Minoshima",
				"album"=>"J-RAVE Nation",
				"circle"=>"S2TB Recording",
				"comment"=>"",
				"year"=>"2012",
			),
			"153" => array(
				"trackname"=>"Rooftop",
				"artist"=>"3dNOW",
				"album"=>"The First",
				"circle"=>"Kusemono Records (CIO)",
				"comment"=>"",
				"year"=>"2012",
			),
			"301" => array(
				"trackname"=>"Crazy Climber",
				"artist"=>"Traffic Jammies",
				"album"=>"REGARDS",
				"circle"=>"NiTEFLARE",
				"comment"=>"",
				"year"=>"2011",
			),
			"665" => array(
				"trackname"=>"Lick",
				"artist"=>"Ryo Ohnuki",
				"album"=>"GAIN / Semi-Automatic",
				"circle"=>"DOWN FORCE RECORDS",
				"comment"=>"",
				"year"=>"2007",
			),
			"800" => array(
				"trackname"=>"Catch me if you can",
				"artist"=>"t+pazolite",
				"album"=>"GottaMaze2",
				"circle"=>"C.H.S",
				"comment"=>"",
				"year"=>"2009",
			),
			"905" => array(
				"trackname"=>"Feeling You (Kirin Remix)",
				"artist"=>"DJ Amane",
				"album"=>"Feeling You EP",
				"circle"=>"Amazing Records",
				"comment"=>"",
				"year"=>"2013",
			),
			"1144" => array(
				"trackname"=>"Electricity",
				"artist"=>"源屋",
				"album"=>"Operation Unrestricted -overture-",
				"circle"=>"MINAMOTRANCE",
				"comment"=>"",
				"year"=>"2012",
			),
			"1327" => array(
				"trackname"=>"TANO*C TOUR 2013 the Anthem (Alinut Remix)",
				"artist"=>"HARDCORE TANO*C Allstars",
				"album"=>"TANO*C TOUR 2013 the Anthem",
				"circle"=>"HARDCORE TANO*C",
				"comment"=>"",
				"year"=>"2013",
			),
			"1660" => array(
				"trackname"=>"first time (aran Remix)",
				"artist"=>"DJ Genki",
				"album"=>"SKETCH UP! REMIXIES",
				"circle"=>"SKETCH UP! Recordings",
				"comment"=>"",
				"year"=>"2012",
			),
			"2030" => array(
				"trackname"=>"Sepia",
				"artist"=>"Massive New Krew vs Hommarju",
				"album"=>"Future Massive Androidz",
				"circle"=>"Massive CircleZ",
				"comment"=>"",
				"year"=>"2012",
			),
			"2054" => array(
				"trackname"=>"Mind Mapping",
				"artist"=>"Ryu☆",
				"album"=>"starmine Disc 01:ORIGINAL ALBUM SIDE",
				"circle"=>"",
				"comment"=>"It was hard to picking this out of the mix. 3: ",
				"year"=>"2009",
			),
			"2201" => array(
				"trackname"=>"Drop Shot",
				"artist"=>"aran",
				"album"=>"Round Up Crystals EP",
				"circle"=>"",
				"comment"=>"",
				"year"=>"2012",
			),
			"2415" => array(
				"trackname"=>"iの数式",
				"artist"=>"D-[R]AM",
				"album"=>"Candy Highway",
				"circle"=>"AVSS",
				"comment"=>"",
				"year"=>"2007",
			),
			"2566" => array(
				"trackname"=>"FINALE Vol.Tiro",
				"artist"=>"nam5",
				"album"=>"Dance With The Angels",
				"circle"=>"FOX RAVEL",
				"comment"=>"",
				"year"=>"2011",
			),
			"2674" => array(
				"trackname"=>"Artemis Blue (ALR Remix)",
				"artist"=>"Barbarian On The Groove feat. 真理絵",
				"album"=>"SUPER SHOT4 -美少女ゲームリミックスコレクション‐",
				"circle"=>"SHOT MUSIC",
				"comment"=>"",
				"year"=>"2011",
			),
			"2777" => array(
				"trackname"=>"Vakzin",
				"artist"=>"Dyes Iwasaki",
				"album"=>"Isolation",
				"circle"=>"en",
				"comment"=>"Will it blend? That is the question.",
				"year"=>"2012",
			),
			"2943" => array(
				"trackname"=>"dubstep chime",
				"artist"=>"mononofrog_4sk",
				"album"=>"nu low freq",
				"circle"=>"Voltecks",
				"comment"=>"",
				"year"=>"2012",
			),
			"3079" => array(
				"trackname"=>"freezia",
				"artist"=>"LuL",
				"album"=>"purotorecords IIDX #1 -original music compilation- Disc2",
				"circle"=>"purotorecords",
				"comment"=>"",
				"year"=>"2011",
			),
			"3277" => array(
				"trackname"=>"Launch World (Entropy13 Remix)",
				"artist"=>"DJ TECHNORCH",
				"album"=>"I WANNA BE A HAPPY",
				"circle"=>"999 Recordings",
				"comment"=>"",
				"year"=>"2012",
			),
			"3368" => array(
				"trackname"=>"最後に何キロバイトかの音に愛をこめ、あなたに贈りましょう。",
				"artist"=>"撲殺少女工房",
				"album"=>"Bit Shoujo Komputer",
				"circle"=>"MOB SQUAD TOKYO",
				"comment"=>"",
				"year"=>"2010",
			),
		),
	),

	"papa_petes_-_first_stage.mp3"=>array(
		"title"=>"Papa Pete's: First Stage! <3",
		"date"=> "10/21/2013",
		"bpm"=>"170",
		"offset"=>"",
		"comment" => "J-core 170bpm hardcore style",
		"description" => 	"This was my first show at papapetes. This was my first time playing J-core for an audience that didn't know ".
							"anything about it. The reception went well, but I felt there was still a lot of room for improvement in my ".
							"choices of selection. This set focused specifically on Hardcore Style, which is about 170bpm.",
		"cover"=>"papapetes1.png",
		"markers"=>array(
			"11"=>array(
				"trackname"=> "Find Yourself (源屋 Remix)",
				"artist" => "源屋",
				"album" => "MINAMOTRANCE CORE Re：BOOT",
				"circle" => "",
				"comment"=> "Seemed like the perfect starter for this show.",
				"year"=>"2011",
			),
			"283"=>array(
				"trackname"=>"smiley*smiley",
				"artist" => "P*Light",
				"album" => "Bright Colors",
				"circle" => "HARDCORE TANO*C",
				"comment" => "Oh~ always part~ay <3 It's a very addictive song.",
				"year"=>"2012",
			),
			"590" => array(
				"trackname"=>"Lips",
				"artist"=>"DJ Genki",
				"album"=>"凸×凹",
				"circle" => "SKETCH UP! Recordings",
				"comment"=>"LOL, that album name.",
				"year"=>"2011",
			),
			"805" => array(
				"trackname"=>"smoke",
				"artist"=>"P*Light",
				"album"=>"P*Style 3.50",
				"circle" => "pichnopop",
				"comment"=>"Because, you know, in a way, surfing the internet, is for Hardcore pornos.",
				"year"=>"2011",
			),
			"1125" => array(
				"trackname"=>"Psychedelic Syndrome (源屋 Remix)",
				"artist"=>"REDALiCE",
				"album"=>"CRIMSON HARDCORE",
				"circle"=>"HARDCORE TANO*C",
				"comment"=>"This is not one of READAliCE's best, he's one of my favorite DJ's, but it's just all I could find of his that was in english. One of my intents for this mix was to get as many of my personal favorite DJ's as I could in this.",
				"year"=>"2009",
			),
			"1238" => array(
				"trackname"=>"Holy Battle",
				"artist"=>"M-Project",
				"album"=>"Desperate!!",
				"circle"=>"RaverRose",
				"comment"=>"I chose this song because of the FFVI song (Atma) within it, but these guys... are responsible for issues with my youtube account.",
				"year"=>"2004",
			),
			"1500" => array(
				"trackname"=>"MADDEST CHICK'NDOM SAMPLER",
				"artist"=>"MADDEST CHICK'NDOM",
				"album"=>"THE DAY OF HARDCORE VOL.2",
				"circle"=>"Guhroovy",
				"comment"=>"This circle is apparently the same people as the previous track, also on my 'No longer use or promote' list.",
				"year"=>"2007	",
			),
			"1571" => array(
				"trackname"=>"Vengeful Dream",
				"artist"=>"nadeco",
				"album"=>"SKETCH BOOK! Anthology - Disc 02 Friendship Side",
				"circle"=>"SKETCH UP! Recordings",
				"comment"=>"",
				"year"=>"2010",
			),
			"2073" => array(
				"trackname"=>"Maddness Fucker",
				"artist"=>"源屋",
				"album"=>"MINAMOTRANCE CORE 斬!!!",
				"circle"=>"MINAMOTRANCE",
				"comment"=>"MADDEST CHICK'NDOM still playing! :p",
				"year"=>"2008",
			),
			"2377" => array(
				"trackname"=>"Serotonin 2008",
				"artist"=>"Joshka",
				"album"=>"HARDCORE SYNDROME 2",
				"circle"=>"HARDCORE TANO*C",
				"comment"=>"Still MADDEST CHICK'NDOM playing, and ... I have no idea if this is where this song started, just a best guess.",
				"year"=>"2008",
			),
			"2747" => array(
				"trackname"=>"PRELUDE",
				"artist"=>"DJ Noriken vs P*Light",
				"album"=>"RADIANCE",
				"circle"=>"HARDCORE TANO*C",
				"comment"=>"",
				"year"=>"2012",
			),
			"3028" => array(
				"trackname"=>"Never",
				"artist"=>"DJ 490",
				"album"=>"Allkore Riot Squad Vol. 3 Hardcore Side",
				"circle"=>"Allkore",
				"comment"=>"I really should have played this sooner in the setlist, but I was tyring to mix, more than play good stuff.",
				"year"=>"2012",
			),
			"3303" => array(
				"trackname"=>"Sarcomite",
				"artist"=>"Alabaster",
				"album"=>"HARDCORE SYNDROME 3",
				"circle"=>"HARDCORE TANO*C",
				"comment"=>"",
				"year"=>"2009",
			),
			"3443" => array(
				"trackname"=>"I'm So Happy (kors k Remix)",
				"artist"=>"Ryu☆",
				"album"=>"The 4th EP",
				"circle"=>"S2TB Recording",
				"comment"=>"This isn't DDR. :p",
				"year"=>"2012",
			),
			"3740" => array(
				"trackname"=>"to Luv me I*** for u. (mangled by Betwixt & Between)",
				"artist"=>"t+pazolite",
				"album"=>"TANO*C REMIXES 2",
				"circle"=>"",
				"comment"=>"HARDCORE TANO*C",
				"year"=>"2010",
			),
			"3854" => array(
				"trackname"=>"regenerate Sky",
				"artist"=>"Noizenecio",
				"album"=>"SPEED BALL Z",
				"circle"=>"HARDCORE TANO*C",
				"comment"=>"",
				"year"=>"2009",
			),
			"4343" => array(
				"trackname"=>"Boku",
				"artist"=>"USAO",
				"album"=>"Otaku Hardcore Revolution 2011",
				"circle"=>"",
				"comment"=>"Seriously, don't watch an anime called Boku (Boku, Boku no Pico, Boku no Pico no Chico, just don't do it, it's Shota-hentai)",
				"year"=>"2011",
			),
			"10000" => array(
				"trackname"=>"Storm Cruizer",
				"artist"=>"DJ Noriken",
				"album"=>"Japanese Stream Hardcore Vol.1",
				"circle"=>"Japanese Stream Hardcore",
				"year"=>"2011",
				"comment"=>"It's somewhere in there somewhere, if you know, please let me know.",
			),
			"10001" => array(
				"trackname"=>"Silence",
				"artist"=>"源屋",
				"album"=>"MINAMOTRANCE CORE QUAD!!!!",
				"circle"=>"MINAMOTRANCE",
				"year"=>"2009",
				"comment"=>"It's somewhere in there somewhere, if you know, please let me know.",
			),
			"10002" => array(
				"trackname"=>"Band The Teacher",
				"artist"=>"Shox",
				"album"=>"Makina Hardcore Pandemic 2",
				"circle"=>"Makinaforce Recordings",
				"year"=>"2011",
				"comment"=>"It's somewhere in there somewhere, if you know, please let me know.",
			),
			"10003" => array(
				"trackname"=>"Shards of The Future",
				"artist"=>"Alabaster",
				"album"=>"Shards of The Future",
				"circle"=>"Monochrome & Colored Records",
				"year"=>"2009",
				"comment"=>"It's somewhere in there somewhere, if you know, please let me know.",
			),
		),
	),
);
$sql = 'DELETE FROM "dj_tracks"';
$db->query($sql);
$sql = "SELECT setval('dj_tracks_id_seq',1)";
$db->query($sql);
$sql = 'DELETE FROM "dj_albums"';
$db->query($sql);
$sql = "SELECT setval('dj_albums_id_seq',1)";
$db->query($sql);
//die("yelp");
foreach($info as $file=>$album) {
	$sql = 'INSERT INTO "dj_albums" ("file","title","date","bpm","offset","comment","description","cover") VALUES('.
		"'".$db->sanitize($file)."',".
		"'".$db->sanitize($album["title"])."',".
		"'".$db->sanitize($album["date"])."',".
		doubleval($album["bpm"]).",".
		doubleval($album["offset"]).",".
		"'".$db->sanitize($album["comment"])."',".
		"'".$db->sanitize($album["description"])."',".
		"'".$db->sanitize($album["cover"])."')";
	$db->query($sql);
	$id = $db->lastId("dj_albums");
	foreach($album["markers"] as $time=>$track){
		$sql = 'INSERT INTO "dj_tracks" ("dj_albums_id","position","trackname","artist","album","circle","year","comment") VALUES('.
			$id.",".
			doubleval($time).",".
			"'".$db->sanitize($track["trackname"])."',".
			"'".$db->sanitize($track["artist"])."',".
			"'".$db->sanitize($track["album"])."',".
			"'".$db->sanitize($track["circle"])."',".
			intval($track["year"]).",".
			"'".$db->sanitize($track["comment"])."')";
		$db->query($sql);
	}
}
?>